### ISSUE TITLE
null is not an object

### ISSUE THREAD

**Issue by katekate902** [busfor/react-native-apay#1]
When calling the ApplePay.canMakePayments, error: null is not an object. is occurred. 

How can I fix the issue?

**Comment by sorokin0andrey** [comment]
Hi @katekate902! Please give me more info about your rn version, real device or simulator, ios version and error screenshot. I will try to help you

**Comment by katekate902** [comment]
RN Version: 0.59.10
Real Device: iphone 6S plus
Simulator: iphone Xs
iOS Version: iOS 12.0
Screen Capture: 
![Capture](https://user-images.githubusercontent.com/43260717/61522036-19de2e00-aa44-11e9-891c-7535266dcd82.PNG)

**Comment by katekate902** [comment]
This is my first time using react native for developing the ApplePay 
I have already set up the merchant ID but seems not work. 
Am I missing something that the module need? Or should I create a sendbox in apple developer for the applepay?

**Comment by katekate902** [comment]
I have found the problem. =)
$ react-native link react-native-apay > this code is not linked the xcode project into my project although It is shown "The project is already linked"
I need to manually link the project by myself.
![Capture](https://user-images.githubusercontent.com/43260717/61528209-c45c4e00-aa50-11e9-98ba-14bc126d9b6d.PNG)
