### ISSUE TITLE
The card can not purchase but the transaction details are got.

### ISSUE THREAD

**Issue by katekate902** [busfor/react-native-apay#2]
RN Version: 0.59.10
Real Device: iphone 6S plus / iphone XR
Simulator: iphone Xs
iOS Version: iOS 12.0

The module can get all the transaction detail after clicking to pay. However, the card have not finished the transaction yet. No money is paid and none of the transaction SMS is received. 

![Untitled](https://user-images.githubusercontent.com/43260717/62608912-6033f800-b933-11e9-9ab5-1636c3f946e9.png)
All transaction details are got but in fact there is not any transaction.

![Untitled](https://user-images.githubusercontent.com/43260717/62609441-58c11e80-b934-11e9-8127-f8cb1eb97008.png)
The code I have done.

**Comment by katekate902** [comment]
Does anyone help to update?

**Comment by sorokin0andrey** [comment]
Hello @katekate902 ! Learn how Apple Pay works. Apple Pay only provides a payment token (an analogue of the card data), which you must transfer to your merchant in order for it to pay for this token
